{
 "title": "creatingly-reports",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values()" } },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info,node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Max memory over last two days", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "The Max memory of pod over two days",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(sum(node_namespace_pod_container:container_memory_working_set_bytes{namespace=~\"apps|dbs\"}) by (pod)[2d:])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "average CPU usage of all pods",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"apps|dbs\"}) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg(node_namespace_pod_container:container_memory_working_set_bytes{cluster=\"$cluster\", node=~\"$node\", container!=\"\",namespace=~\"apps|dbs\"}) by (pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Max I/O calls to a pod in a minute",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "IOPS(Reads+Writes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "ceil(sum by(pod) (rate(container_fs_reads_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", cluster=\"$cluster\", namespace=~\"apps|dbs\"}[1m]) + rate(container_fs_writes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", cluster=\"$cluster\", namespace=~\"apps|dbs\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total I/O calls in a day",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum by(pod) (sum_over_time(container_fs_reads_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", cluster=\"$cluster\", namespace=~\"apps|dbs\"}[1d:]) + sum_over_time(container_fs_writes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", cluster=\"$cluster\", namespace=~\"apps|dbs\"}[1d:])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Storage volume usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "pv used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (mountpoint) ( (node_filesystem_size_bytes{job=\"node-exporter\", cluster=\"$cluster\", fstype!=\"\", mountpoint=\"/\"}) - (node_filesystem_avail_bytes{job=\"node-exporter\", cluster=\"$cluster\", fstype!=\"\", mountpoint=\"/\"}))\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}