{
 "title": "creatingly-project-1",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values()" } },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info,node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Namespace-wise live usage of CPU, Memory, storage and I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"apps|dbs\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=~\"apps|dbs\", container!=\"\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IOPS(Reads+Writes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "ceil(sum by(namespace) (rate(container_fs_reads_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", namespace=~\"apps|dbs\"}[$__rate_interval]) + rate(container_fs_writes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", namespace=~\"apps|dbs\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ThroughPut(Read+Write)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(container_fs_reads_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", cluster=\"$cluster\", namespace=~\"apps|dbs\"}[$__rate_interval]) + rate(container_fs_writes_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", cluster=\"$cluster\", namespace=~\"apps|dbs\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod-wise live usage of CPU, Memory, storage and I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{cluster=\"$cluster\", node=~\"$node\", resource=\"cpu\"})",
     "legendFormat": "max capacity"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", node=~\"$node\",namespace=~\"apps|dbs\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{cluster=\"$cluster\", node=~\"$node\", resource=\"memory\"})",
     "legendFormat": "max capacity"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{cluster=\"$cluster\", node=~\"$node\", container!=\"\",namespace=~\"apps|dbs\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "IOPS(Reads+Writes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "ceil(sum by(pod) (rate(container_fs_reads_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", cluster=\"$cluster\", namespace=~\"apps|dbs\"}[$__rate_interval]) + rate(container_fs_writes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", cluster=\"$cluster\", namespace=~\"apps|dbs\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}