apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-db-pvc
  namespace: dbs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
